"""Generate one HTML page per term, so a browser gets prose instead of Turtle.

Every rule in the w3id rewrite is gated on an RDF `Accept` header, so a browser
asking for https://w3id.org/pkm/vocab/DayMealPlan fell through to the catch-all
and 404'd. These pages are what it lands on instead: same URI, same concept, a
representation a person can read. RDF clients are unaffected -- their rule
carries `[L]` and still 303s to `vocab/terms/{Term}.ttl`.

The pages sit beside the Turtle in `vocab/terms/` and carry a `permalink` that
moves them to `/vocab/{Term}/`, which is the URI. Jekyll writes
`_site/vocab/{Term}/index.html`; Pages serves that for the extensionless URI,
adding the trailing slash itself with a 301.

Generated wholesale, unlike the index pages: there is no hand-written prose in a
term page to preserve, so there are no splice markers. Every link is relative,
so the tree resolves under any baseurl -- and under none, which is what Pages
serves this repo with.

Deliberately close to `notes.py`, which does the same extraction for Obsidian.
The two should share it eventually; they do not yet because that module writes
into a vault with Sync and Publish enabled, and a refactor there is not worth
folding into this change.
"""

from __future__ import annotations

import re
from pathlib import Path

from rdflib import Graph, URIRef
from rdflib.namespace import DCTERMS, FOAF, OWL, RDFS, SKOS

from . import ISO_BROADER, ISO_QUALIFIER, Vocabulary, wrap
from .split import TERMS_DIR

__all__ = ["render_page", "render_pages", "write_pages"]

NOTICE = ("<!-- Generated by `make build`. Do not edit: rewritten in place on "
          "every build. The term is maintained in the SKOS Editor export. -->")

#: Local names that would collide with a page the site already publishes.
RESERVED = {"index", "terms"}


def _q(value: str) -> str:
    """An always-quoted YAML scalar. Labels contain colons often enough."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


#: Liquid runs over these pages before Markdown does, so text that mentions a
#: template delimiter is read as a tag and disappears. Three scope notes say
#: `{{ ... }}` while describing Jinja2 syntax, and lost it silently -- the page
#: built without error and rendered "with syntax () that are used to".
_LIQUID = re.compile(r"\{\{|\{%")


def _prose(text: str) -> str:
    """Graph text, fenced off from Liquid when it looks like a tag.

    Only when it has to be: `raw` is invisible once rendered, but it is still
    noise in the source, and 238 of the 241 pages have no reason to carry it.
    Front matter is exempt -- Jekyll does not run Liquid over YAML.
    """
    return f"{{% raw %}}{text}{{% endraw %}}" if _LIQUID.search(text) else text


def _first(vocab: Vocabulary, subject: URIRef, *props) -> str | None:
    for prop in props:
        value = vocab.graph.value(subject, prop)
        if value is not None:
            return str(value).strip()
    return None


def _all(vocab: Vocabulary, subject: URIRef, prop) -> list[str]:
    return sorted(str(o) for o in vocab.graph.objects(subject, prop))


def _link(vocab: Vocabulary, uri: URIRef) -> str:
    """A relative link to another term's page, or a bare URI if it is external."""
    if not vocab.is_local(uri):
        return f"<{uri}>"
    return f"[{vocab.label(uri)}](../{vocab.local_name(uri)}/)"


def render_page(vocab: Vocabulary, uri: URIRef, *,
                children: dict[URIRef, list[URIRef]],
                parents: dict[URIRef, list[URIRef]],
                in_collection: dict[URIRef, list[URIRef]],
                collections: set[URIRef]) -> str:
    """One term page: Jekyll front matter, then the term as prose."""
    graph = vocab.graph
    local = vocab.local_name(uri)
    label = vocab.label(uri)
    is_collection = uri in collections
    kind = "collection" if is_collection else "concept"

    definition = _first(vocab, uri, SKOS.definition)
    scope = _first(vocab, uri, SKOS.scopeNote)
    note = _first(vocab, uri, SKOS.note, RDFS.comment)
    created = _first(vocab, uri, DCTERMS.created)
    modified = _first(vocab, uri, DCTERMS.modified)
    alts = _all(vocab, uri, SKOS.altLabel)
    related = sorted((o for o in graph.objects(uri, SKOS.related) if vocab.is_local(o)),
                     key=vocab.label)
    members = sorted((o for o in graph.objects(uri, SKOS.member) if vocab.is_local(o)),
                     key=vocab.label)
    see_also = _all(vocab, uri, RDFS.seeAlso)
    matches = _all(vocab, uri, SKOS.relatedMatch)
    is_top = bool(list(graph.objects(uri, SKOS.topConceptOf)))
    deprecated = bool(list(graph.objects(uri, OWL.deprecated)))

    # ISO 25964 specialisations are sub-properties of skos:broader, so a
    # qualified parent is also a broader parent. Annotate in place rather than
    # list the same parent twice under two headings.
    qualifier: dict[URIRef, str] = {}
    for prop in ISO_BROADER:
        for parent in graph.objects(uri, prop):
            if vocab.is_local(parent):
                qualifier[parent] = ISO_QUALIFIER[prop]

    out: list[str] = [
        "---",
        "layout: default",
        f"title: {_q(label)}",
        f"permalink: /vocab/{local}/",
        "---",
        "",
        NOTICE,
        "",
        f"# {_prose(label)}",
        "",
    ]

    where = f"SKOS {kind} in the [PKM Vocabulary](../)"
    if is_top:
        where += ", one of its top concepts"
    out += [f"_{where}._", ""]

    if deprecated:
        replaced = _all(vocab, uri, DCTERMS.isReplacedBy)
        out += ["**Deprecated.** This term is retired. Its URI keeps resolving, "
                "so existing links do not rot, but do not use it in new work."]
        out += [f"Replaced by {_link(vocab, URIRef(r))}." for r in replaced]
        out += [""]

    if definition:
        out += [_prose(definition), ""]
    elif note:
        out += [_prose(note), ""]

    if alts:
        out += [f"**Also known as:** {_prose(', '.join(alts))}", ""]

    if scope:
        out += ["## Scope note", "", _prose(scope), ""]

    if note and definition:
        out += ["## Note", "", _prose(note), ""]

    if uri in parents:
        out += ["## Broader", ""]
        for parent in parents[uri]:
            tag = f" — {qualifier[parent]} (ISO 25964)" if parent in qualifier else ""
            out.append(f"- {_link(vocab, parent)}{tag}")
        out.append("")

    if uri in children:
        out += ["## Narrower", ""]
        out += [f"- {_link(vocab, kid)}" for kid in children[uri]]
        out.append("")

    if related:
        out += ["## Related", "", "_Associated, not hierarchical._", ""]
        out += [f"- {_link(vocab, r)}" for r in related]
        out.append("")

    if members:
        out += [f"## Members ({len(members)})", ""]
        out += [f"- {_link(vocab, m)}" for m in members]
        out.append("")

    if uri in in_collection:
        out += ["## In these collections", "",
                "_Groupings; they carry no hierarchical meaning._", ""]
        out += [f"- {_link(vocab, c)}" for c in in_collection[uri]]
        out.append("")

    if see_also or matches:
        out += ["## Elsewhere", ""]
        out += [f"- See also <{u}>" for u in see_also]
        out += [f"- Related match <{u}>" for u in matches]
        out.append("")

    # The point of the whole exercise: this page and the Turtle are the same
    # URI, and a reader who wants the data should be able to see how to ask for
    # it without first having to know what content negotiation is.
    out += [
        "## This term in RDF",
        "",
        f"- **URI** — `{vocab.base}{local}` (`{vocab.curie(uri)}`)",
        f"- **Turtle** — [`{TERMS_DIR}/{local}.ttl`](../{TERMS_DIR}/{local}.ttl)",
        f"- **Whole vocabulary** — [`pkm-vocab.ttl`](../pkm-vocab.ttl)",
        "",
        "That URI serves this page to a browser and RDF to a client that asks "
        "for it, so one link works for both:",
        "",
        "```",
        f"curl -L -H 'Accept: text/turtle' {vocab.base}{local}",
        "```",
        "",
    ]

    out.append("---")
    out.append("")
    meta = [f"`{vocab.curie(uri)}`"]
    if created:
        meta.append(f"created {created[:10]}")
    if modified:
        meta.append(f"modified {modified[:10]}")
    creator = _creator(vocab, uri)
    if creator:
        meta.append(creator)
    out.append(" · ".join(meta))
    out.append("")
    out.append("Maintained in the SKOS source, not on this page. "
               "[All terms](../) · [Namespace home](../../)")
    out.append("")

    return "\n".join(out)


def _creator(vocab: Vocabulary, uri: URIRef) -> str:
    """The creator's name, linked to the agents page, if it resolves to one."""
    agent = vocab.graph.value(uri, DCTERMS.creator)
    if not isinstance(agent, URIRef):
        return str(agent) if agent is not None else ""
    name = _first(vocab, agent, FOAF.name, DCTERMS.title, RDFS.label)
    anchor = str(agent).split("#", 1)[-1]
    return f"by [{name or anchor}](../../agents/)"


def render_pages(vocab: Vocabulary, published: Graph) -> dict[str, str]:
    """Every term page, keyed by filename relative to `vocab/terms/`."""
    # Read the facts off the PUBLISHED graph, the way render_vocabulary does,
    # so the pages describe what actually resolves rather than what the editor
    # exported. `wrap` re-derives the scheme and base from it.
    pub = wrap(published, vocab.path)
    if not pub.base:
        pub.base = vocab.base

    collections = set(pub.collections())

    # skos:broader, skos:narrower and the six ISO sub-properties, unioned and
    # normalised to (child, parent) -- so a parent stated only as narrower on
    # the other end still shows up here.
    children: dict[URIRef, list[URIRef]] = {}
    parents: dict[URIRef, list[URIRef]] = {}
    for child, parent in pub.broader_pairs():
        if not (pub.is_local(child) and pub.is_local(parent)):
            continue
        children.setdefault(parent, []).append(child)
        parents.setdefault(child, []).append(parent)
    for index in (children, parents):
        for key in index:
            index[key] = sorted(set(index[key]), key=pub.label)

    # Reverse index: concept -> the collections listing it as a member.
    # skos:member has no inverse, so the statement lives only on the collection.
    in_collection: dict[URIRef, list[URIRef]] = {}
    for collection in collections:
        for member in published.objects(collection, SKOS.member):
            if pub.is_local(member):
                in_collection.setdefault(member, []).append(collection)
    for key in in_collection:
        in_collection[key] = sorted(set(in_collection[key]), key=pub.label)

    pages: dict[str, str] = {}
    for uri in [*pub.concepts(), *pub.collections()]:
        local = pub.local_name(uri)
        if local.lower() in RESERVED:
            raise ValueError(
                f"{uri} has local name {local!r}, which would overwrite an "
                f"existing page at /vocab/{local}/"
            )
        pages[f"{local}.md"] = render_page(
            pub, uri, children=children, parents=parents,
            in_collection=in_collection, collections=collections,
        )
    return pages


def write_pages(vocab: Vocabulary, published: Graph, root: Path) -> list[Path]:
    """Write every term page under `vocab/terms/`.

    Only changed files are rewritten, so a no-op build leaves 241 mtimes alone
    and Jekyll's incremental build has nothing to do.
    """
    terms = root / "vocab" / TERMS_DIR
    terms.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for name, text in sorted(render_pages(vocab, published).items()):
        path = terms / name
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written
