"""Generate the Markdown pages from the published graph.

Everything written here sits between HTML-comment markers, so hand-written
prose in the same file survives a rebuild. A page with no markers gets the
block appended once; after that the block is replaced in place.
"""

from __future__ import annotations

from pathlib import Path

from rdflib import Graph, Literal, URIRef
from rdflib.namespace import DCTERMS, FOAF, RDFS, SKOS

from . import Vocabulary
from .split import TERMS_DIR
from .transform import agent_base, resource_base

__all__ = ["render_vocabulary", "render_resources", "render_agents", "splice"]

BEGIN = "<!-- pkm:begin generated -->"
END = "<!-- pkm:end generated -->"
NOTICE = "<!-- Generated by `make build`. Edits between these markers are overwritten. -->"


def splice(path: Path, body: str) -> Path:
    """Replace the generated block in `path`, or append one if there is none."""
    block = f"{BEGIN}\n{NOTICE}\n\n{body.strip()}\n\n{END}\n"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if BEGIN in text and END in text:
        head, _, rest = text.partition(BEGIN)
        _, _, tail = rest.partition(END)
        text = head + block.rstrip("\n") + tail
    else:
        text = (text.rstrip("\n") + "\n\n" if text.strip() else "") + block
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def _first(graph: Graph, subject, *props) -> str:
    for prop in props:
        value = graph.value(subject, prop)
        if value is not None:
            return str(value).strip()
    return ""


def _link(vocab: Vocabulary, uri: URIRef) -> str:
    return f"[{vocab.label(uri)}]({TERMS_DIR}/{vocab.local_name(uri)}.ttl)"


def render_vocabulary(vocab: Vocabulary, published: Graph) -> str:
    g = published
    concepts = vocab.concepts()
    collections = vocab.collections()

    children: dict[URIRef, set[URIRef]] = {}
    for child, parent in g.subject_objects(SKOS.broader):
        children.setdefault(parent, set()).add(child)

    tops = sorted(g.objects(vocab.scheme, SKOS.hasTopConcept), key=vocab.label)

    lines: list[str] = [
        "## Download",
        "",
        f"- [`pkm-vocab.ttl`](pkm-vocab.ttl) — the whole vocabulary in Turtle "
        f"({len(concepts)} concepts, {len(collections)} collections)",
        f"- One Turtle file per term at `{TERMS_DIR}/{{Term}}.ttl`, which is what "
        "`https://w3id.org/pkm/vocab/{Term}` resolves to for an RDF client",
        "",
        "## Hierarchy",
        "",
        "Nested by `skos:broader`, starting from the top concepts. A term with more "
        "than one parent is listed in full once and cross-referenced after that.",
        "",
    ]

    # A polyhierarchy has no single correct tree. Expanding a shared subtree at
    # every parent would multiply the page, so it is expanded once and pointed
    # at thereafter.
    expanded: set[URIRef] = set()

    def walk(node: URIRef, depth: int) -> None:
        pad = "  " * depth
        kids = sorted(children.get(node, ()), key=vocab.label)
        if node in expanded:
            parents = sorted(
                (p for p in g.objects(node, SKOS.broader) if p in expanded),
                key=vocab.label,
            )
            where = f" — also under {vocab.label(parents[0])}" if parents else ""
            lines.append(f"{pad}- {_link(vocab, node)}{where}")
            return
        expanded.add(node)
        lines.append(f"{pad}- {_link(vocab, node)}")
        for kid in kids:
            walk(kid, depth + 1)

    for top in tops:
        walk(top, 0)

    if collections:
        lines += ["", "## Collections", "",
                  "Groupings that carry no hierarchical meaning — a concept's place in "
                  "the tree above is independent of the collections it belongs to.", ""]
        for coll in sorted(collections, key=vocab.label):
            members = sorted(g.objects(coll, SKOS.member), key=vocab.label)
            # skos:note is where the SKOS Editor puts a collection's description --
            # concepts get skos:definition, collections get the generic note. No
            # concept carries skos:note, so looking for it costs nothing above.
            note = _first(g, coll, SKOS.definition, SKOS.scopeNote, SKOS.note, RDFS.comment)
            lines.append(f"- **{_link(vocab, coll)}**" + (f" — {note}" if note else ""))
            if members:
                joined = ", ".join(_link(vocab, m) for m in members)
                noun = "member" if len(members) == 1 else "members"
                lines.append(f"  <br>{len(members)} {noun}: {joined}")
            else:
                lines.append("  <br>_No members yet._")

    # Concepts and collections together. Four of the collections are not named
    # "...Collection" -- Tech Stack, Note Types, Meal Domain, Semantic Web
    # Standards -- so anyone scanning A-Z for one of those would otherwise have
    # to already know it was a collection to find it.
    lines += ["", "## All terms", "",
              "Every concept and collection in one alphabetical list. Collections are "
              "marked; the hierarchy above shows where the concepts sit.", ""]
    letter = ""
    for uri in sorted([*concepts, *collections],
                      key=lambda u: (vocab.label(u).upper(), vocab.local_name(u))):
        initial = vocab.label(uri)[:1].upper()
        if initial != letter:
            letter = initial
            lines += [f"### {letter}", ""]

        entry = f"- **{_link(vocab, uri)}**"
        if uri in collections:
            members = list(g.objects(uri, SKOS.member))
            noun = "member" if len(members) == 1 else "members"
            entry += f" _(collection, {len(members)} {noun})_"
        alts = sorted(str(a) for a in g.objects(uri, SKOS.altLabel))
        if alts:
            entry += f" _(also: {', '.join(alts)})_"
        definition = _first(g, uri, SKOS.definition, SKOS.scopeNote, SKOS.note)
        if definition:
            entry += f" — {definition}"
        lines.append(entry)

        # skos:member has no inverse, so a concept never states its own
        # membership. Say it here rather than make the reader scan 18 lists.
        if uri in concepts:
            belongs = sorted(g.subjects(SKOS.member, uri), key=vocab.label)
            if belongs:
                joined = ", ".join(_link(vocab, c) for c in belongs)
                lines.append(f"  <br>In: {joined}")

    return "\n".join(lines)


def _metadata_list(vocab: Vocabulary, published: Graph, base: str, rel: str) -> list[str]:
    """One bullet per subject in a hash namespace, newest information first."""
    subjects = sorted(
        {s for s in published.subjects() if isinstance(s, URIRef) and str(s).startswith(base)},
        key=lambda s: _first(published, s, FOAF.name, DCTERMS.title, RDFS.label).lower(),
    )
    lines = []
    for subj in subjects:
        name = _first(published, subj, FOAF.name, DCTERMS.title, RDFS.label) or str(subj)
        page = published.value(subj, FOAF.homepage) or published.value(subj, FOAF.page)
        note = _first(published, subj, RDFS.comment, SKOS.note, DCTERMS.description)
        label = f"[{name}]({page})" if page else name
        anchor = str(subj).split("#", 1)[-1]
        entry = f"- **{label}** — `{rel}#{anchor}`"
        lines.append(entry + (f"<br>{note}" if note else ""))
    return lines


def render_resources(vocab: Vocabulary, published: Graph) -> str:
    entries = _metadata_list(vocab, published, resource_base(vocab), "resources")
    return "\n".join([
        "## Cited documents",
        "",
        "Sources referenced by vocabulary concepts through `dcterms:source`. "
        "Machine-readable at [`index.ttl`](index.ttl).",
        "",
        *entries,
    ])


def render_agents(vocab: Vocabulary, published: Graph) -> str:
    entries = _metadata_list(vocab, published, agent_base(vocab), "agents")
    return "\n".join([
        "## Agents",
        "",
        "People and software credited in the vocabulary through `dcterms:creator`, "
        "`dcterms:contributor`, and `dcterms:publisher`. "
        "Machine-readable at [`index.ttl`](index.ttl).",
        "",
        *entries,
    ])
