"""Generate the Markdown pages from the published graph.

Everything written here sits between HTML-comment markers, so hand-written
prose in the same file survives a rebuild. A page with no markers gets the
block appended once; after that the block is replaced in place.

The vocabulary is rendered as four pages rather than one. It was one page of
721 lines and 51 KB, which is a problem of ordering as much as of length: the
collections sat after 249 lines of hierarchy and "All terms" -- the section a
first-time reader most likely wants -- came last. The namespace front page at
`index.md` does the opposite and does it well, opening on a table of what
exists with a link per row, so the vocabulary landing page is shaped like its
own parent and the three views are sub-pages under `browse/`.

`browse/` rather than `/vocab/hierarchy/` because term URIs are
`/vocab/{Term}`: a flat sub-page would permanently reserve a plausible term
local name and would sit in the slot an RDF client expects a term in. One
reserved name, and it reads as navigation. See `pages.RESERVED`.
"""

from __future__ import annotations

import json
from pathlib import Path

from rdflib import Graph, URIRef
from rdflib.namespace import DCTERMS, FOAF, RDFS, SKOS

from . import Vocabulary
from .pages import _description
from .split import TERMS_DIR
from .transform import agent_base, resource_base

__all__ = [
    "render_vocab_index", "render_hierarchy", "render_collections",
    "render_all_terms", "render_search_index", "render_resources",
    "render_agents", "splice", "spliced", "HUB_NOTICE",
]

BEGIN = "<!-- pkm:begin generated -->"
END = "<!-- pkm:end generated -->"
NOTICE = "<!-- Generated by `make build`. Edits between these markers are overwritten. -->"

#: The hub is written by a different target, so it says so. A notice naming
#: the wrong command is worse than none: it sends whoever finds their edit
#: gone to a target that does not touch the file.
HUB_NOTICE = "<!-- Generated by `make hub`. Edits between these markers are overwritten. -->"

#: Where the browse sub-pages live, relative to `vocab/`. One constant because
#: the landing page links to them, `pages.RESERVED` guards the name, and the
#: Makefile's `site` check has to exclude the built directory from its term
#: count -- three places that must agree.
BROWSE_DIR = "browse"

#: How far a browse page is from `/vocab/`, for term links. The pages are at
#: `/vocab/browse/{view}/`, so a term at `/vocab/Recipe/` is two levels up.
UP = "../../"


def _markers(name: str | None) -> tuple[str, str]:
    """Marker pair for a block, named or not.

    Named blocks exist for the Obsidian hub, which needs two generated regions
    with hand-written prose between them. The unnamed form is unchanged, so
    the three pages that already carry markers are untouched.
    """
    if not name:
        return BEGIN, END
    return (f"<!-- pkm:begin generated: {name} -->",
            f"<!-- pkm:end generated: {name} -->")


def spliced(text: str, body: str, name: str | None = None,
            notice: str = NOTICE) -> str:
    """`text` with the named generated block replaced, or appended if absent.

    Pure, so a caller filling several blocks in one file composes calls and
    writes once -- which is what the Obsidian hub needs.
    """
    begin, end = _markers(name)
    block = f"{begin}\n{notice}\n\n{body.strip()}\n\n{end}\n"
    if begin in text and end in text:
        head, _, rest = text.partition(begin)
        _, _, tail = rest.partition(end)
        return head + block.rstrip("\n") + tail
    return (text.rstrip("\n") + "\n\n" if text.strip() else "") + block


def splice(path: Path, body: str, name: str | None = None) -> Path:
    """Replace a generated block in `path`, or append one if there is none."""
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(spliced(text, body, name), encoding="utf-8")
    return path


def _first(graph: Graph, subject, *props) -> str:
    for prop in props:
        value = graph.value(subject, prop)
        if value is not None:
            return str(value).strip()
    return ""


def _link(vocab: Vocabulary, uri: URIRef, prefix: str = "") -> str:
    """Link to the term's own page rather than to its Turtle.

    These indexes are where most readers arrive, and dropping them into raw
    Turtle is a poor first look at a vocabulary. The Turtle is one hop further
    on, linked from every term page and from Download on the landing page.

    `prefix` is how far the linking page sits from `/vocab/`: empty from the
    landing page, `UP` from a browse page.
    """
    return f"[{vocab.label(uri)}]({prefix}{vocab.local_name(uri)}/)"


def _children(graph: Graph) -> dict[URIRef, set[URIRef]]:
    out: dict[URIRef, set[URIRef]] = {}
    for child, parent in graph.subject_objects(SKOS.broader):
        out.setdefault(parent, set()).add(child)
    return out


def _tops(vocab: Vocabulary, graph: Graph) -> list[URIRef]:
    return sorted(graph.objects(vocab.scheme, SKOS.hasTopConcept), key=vocab.label)


def _subtree(vocab: Vocabulary, graph: Graph, children: dict[URIRef, set[URIRef]],
             node: URIRef, depth: int, expanded: set[URIRef],
             prefix: str) -> list[str]:
    """One node and everything under it, as indented bullets.

    A polyhierarchy has no single correct tree. Expanding a shared subtree at
    every parent would multiply the page, so it is expanded once and pointed
    at thereafter -- which is why `expanded` is threaded through rather than
    rebuilt per call.
    """
    pad = "  " * depth
    if node in expanded:
        parents = sorted(
            (p for p in graph.objects(node, SKOS.broader) if p in expanded),
            key=vocab.label,
        )
        where = f" — also under {vocab.label(parents[0])}" if parents else ""
        return [f"{pad}- {_link(vocab, node, prefix)}{where}"]
    expanded.add(node)
    out = [f"{pad}- {_link(vocab, node, prefix)}"]
    for kid in sorted(children.get(node, ()), key=vocab.label):
        out += _subtree(vocab, graph, children, kid, depth + 1, expanded, prefix)
    return out


def render_vocab_index(vocab: Vocabulary, published: Graph) -> str:
    """The landing page: a table of the three views, then Download.

    Shaped like the namespace front page rather than like a dump of the whole
    vocabulary, which is the change this release is about.
    """
    g = published
    concepts = vocab.concepts()
    collections = vocab.collections()
    tops = _tops(vocab, g)
    total = len(concepts) + len(collections)

    return "\n".join([
        "## Browse",
        "",
        "| View | What it shows |",
        "| --- | --- |",
        f"| [Hierarchy]({BROWSE_DIR}/hierarchy/) | "
        f"{len(tops)} top concepts, nested by `skos:broader` |",
        f"| [Collections]({BROWSE_DIR}/collections/) | "
        f"{len(collections)} groupings that carry no hierarchical meaning |",
        f"| [All terms]({BROWSE_DIR}/all/) | "
        f"{total} concepts and collections, A–Z, with definitions |",
        "",
        "Every term also has a page of its own at "
        "`https://w3id.org/pkm/vocab/{Term}`.",
        "",
        "## Download",
        "",
        f"- [`pkm-vocab.ttl`](pkm-vocab.ttl) — the whole vocabulary in Turtle "
        f"({len(concepts)} concepts, {len(collections)} collections)",
        "- One page per term at `https://w3id.org/pkm/vocab/{Term}` — the same URI "
        "serves a readable page to a browser and Turtle to an RDF client",
        f"- The per-term Turtle on its own at `{TERMS_DIR}/{{Term}}.ttl`",
        f"- [`search.json`](search.json) — every term's label, kind and "
        f"definition in one file, which is what the search box on these pages reads",
    ])


def render_hierarchy(vocab: Vocabulary, published: Graph) -> str:
    """The tree, one collapsible block per top concept.

    `<details>` rather than JavaScript because this Markdown renders in three
    places -- the Pages site, the GitHub repo view of the same file, and
    Obsidian -- and `<details>` works in all three where a script works in one.

    Collapsed, with the eight summaries as the open top level: expanding all
    eight would put the 249 lines back. `markdown="1"` is load-bearing --
    kramdown does not look for Markdown inside a block-level HTML element
    without it, and would ship each subtree as one run-together paragraph from
    a source file that reads correctly either way.
    """
    g = published
    children = _children(g)
    expanded: set[URIRef] = set()
    lines: list[str] = []

    for top in _tops(vocab, g):
        body = _subtree(vocab, g, children, top, 0, expanded, UP)
        # body[0] is the top concept itself; the rest are its descendants, and
        # that count is what a reader is deciding whether to expand.
        below = len(body) - 1
        if not below:
            lines += body
            continue
        plural = "" if below == 1 else "s"
        lines += [
            '<details markdown="1">',
            f"<summary>{vocab.label(top)} — {below} narrower term{plural}</summary>",
            "",                       # kramdown needs this to start a list
            *body,
            "",
            "</details>",
            "",
        ]

    return "\n".join(lines).rstrip("\n")


def render_collections(vocab: Vocabulary, published: Graph) -> str:
    """The collections and their members."""
    g = published
    lines: list[str] = []
    for coll in sorted(vocab.collections(), key=vocab.label):
        members = sorted(g.objects(coll, SKOS.member), key=vocab.label)
        # skos:note is where the SKOS Editor puts a collection's description --
        # concepts get skos:definition, collections get the generic note. No
        # concept carries skos:note, so looking for it costs nothing above.
        note = _first(g, coll, SKOS.definition, SKOS.scopeNote, SKOS.note, RDFS.comment)
        lines.append(f"- **{_link(vocab, coll, UP)}**" + (f" — {note}" if note else ""))
        if members:
            joined = ", ".join(_link(vocab, m, UP) for m in members)
            noun = "member" if len(members) == 1 else "members"
            lines.append(f"  <br>{len(members)} {noun}: {joined}")
        else:
            lines.append("  <br>_No members yet._")
    return "\n".join(lines)


def render_all_terms(vocab: Vocabulary, published: Graph) -> str:
    """Every concept and collection, A-Z, behind an index of initials.

    Concepts and collections together. Four of the collections are not named
    "...Collection" -- Tech Stack, Note Types, Meal Domain, Semantic Web
    Standards -- so anyone scanning A-Z for one of those would otherwise have
    to already know it was a collection to find it.
    """
    g = published
    concepts = vocab.concepts()
    collections = set(vocab.collections())
    ordered = sorted([*concepts, *collections],
                     key=lambda u: (vocab.label(u).upper(), vocab.local_name(u)))

    # The A-Z headings have carried anchors since the first release and nothing
    # linked to them, which made the alphabetical view unnavigable on a page
    # 400 lines long. Only the initials that exist, so no link is a dead end.
    initials = sorted({vocab.label(u)[:1].upper() for u in ordered})
    lines = [" · ".join(f"[{i}](#{i.lower()})" for i in initials), ""]

    letter = ""
    for uri in ordered:
        initial = vocab.label(uri)[:1].upper()
        if initial != letter:
            letter = initial
            lines += [f"### {letter}", ""]

        entry = f"- **{_link(vocab, uri, UP)}**"
        if uri in collections:
            members = list(g.objects(uri, SKOS.member))
            noun = "member" if len(members) == 1 else "members"
            entry += f" _(collection, {len(members)} {noun})_"
        alts = sorted(str(a) for a in g.objects(uri, SKOS.altLabel))
        if alts:
            entry += f" _(also: {', '.join(alts)})_"
        definition = _first(g, uri, SKOS.definition, SKOS.scopeNote, SKOS.note)
        if definition:
            entry += f" — {definition}"
        lines.append(entry)

        # skos:member has no inverse, so a concept never states its own
        # membership. Say it here rather than make the reader scan 18 lists.
        if uri not in collections:
            belongs = sorted(g.subjects(SKOS.member, uri), key=vocab.label)
            if belongs:
                joined = ", ".join(_link(vocab, c, UP) for c in belongs)
                lines.append(f"  <br>In: {joined}")

    return "\n".join(lines)


#: Definitions are cut shorter for search than for a link card: these are
#: one-line results under an input, not the whole of a preview.
_SEARCH_MAX = 120


def render_search_index(vocab: Vocabulary, published: Graph) -> str:
    """Every term as one JSON record, for the search box.

    Pages runs Jekyll in safe mode against a fixed plugin allowlist, so a
    search plugin is not available. A generated JSON file plus vanilla JS needs
    no plugin, and this is the file.

    `url` is relative to `/vocab/`, not to the page doing the search: the box
    appears on the landing page, on three browse pages and on 241 term pages,
    which sit at two different depths. The layout passes the resolved
    `/vocab/` base in, so one relative value works from all of them.
    """
    g = published
    collections = set(vocab.collections())
    records = []
    for uri in sorted([*vocab.concepts(), *collections],
                      key=lambda u: (vocab.label(u).upper(), vocab.local_name(u))):
        definition = _first(g, uri, SKOS.definition, SKOS.scopeNote, SKOS.note)
        record = {
            "label": vocab.label(uri),
            "url": f"{vocab.local_name(uri)}/",
            "kind": "collection" if uri in collections else "concept",
        }
        alts = sorted(str(a) for a in g.objects(uri, SKOS.altLabel))
        if alts:
            record["alts"] = alts
        if definition:
            record["definition"] = _description(definition, _SEARCH_MAX)
        records.append(record)
    return json.dumps(records, ensure_ascii=False, indent=0, separators=(",", ":"))


def _metadata_list(vocab: Vocabulary, published: Graph, base: str, rel: str) -> list[str]:
    """One bullet per subject in a hash namespace, newest information first."""
    subjects = sorted(
        {s for s in published.subjects() if isinstance(s, URIRef) and str(s).startswith(base)},
        key=lambda s: _first(published, s, FOAF.name, DCTERMS.title, RDFS.label).lower(),
    )
    lines = []
    for subj in subjects:
        name = _first(published, subj, FOAF.name, DCTERMS.title, RDFS.label) or str(subj)
        page = published.value(subj, FOAF.homepage) or published.value(subj, FOAF.page)
        note = _first(published, subj, RDFS.comment, SKOS.note, DCTERMS.description)
        label = f"[{name}]({page})" if page else name
        anchor = str(subj).split("#", 1)[-1]
        entry = f"- **{label}** — `{rel}#{anchor}`"
        lines.append(entry + (f"<br>{note}" if note else ""))
    return lines


def render_resources(vocab: Vocabulary, published: Graph) -> str:
    entries = _metadata_list(vocab, published, resource_base(vocab), "resources")
    return "\n".join([
        "## Cited documents",
        "",
        "Sources referenced by vocabulary concepts through `dcterms:source`. "
        "Machine-readable at [`index.ttl`](index.ttl).",
        "",
        *entries,
    ])


def render_agents(vocab: Vocabulary, published: Graph) -> str:
    entries = _metadata_list(vocab, published, agent_base(vocab), "agents")
    return "\n".join([
        "## Agents",
        "",
        "People and software credited in the vocabulary through `dcterms:creator`, "
        "`dcterms:contributor`, and `dcterms:publisher`. "
        "Machine-readable at [`index.ttl`](index.ttl).",
        "",
        *entries,
    ])
